// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index", // Specifing this without additional parameters here will default to _category_.json in each folder
      },
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started", // '.' means the current docs folder
        },
      ],
    },
    {
      type: "category",
      label: "Advanced",
      link: {
        type: "generated-index", // Specifing this without additional parameters here will default to _category_.json in each folder
      },
      items: [
        {
          type: "autogenerated",
          dirName: "advanced", // '.' means the current docs folder
        },
      ],
    },
    {
      type: "category",
      label: "Tutorial - Basics",
      link: {
        type: "generated-index", // Specifing this without additional parameters here will default to _category_.json in each folder
      },
      items: [
        {
          type: "autogenerated",
          dirName: "tutorial-basics", // '.' means the current docs folder
        },
      ],
    },
  ],
  apiSidebar: [
    {
      type: "category",
      label: "Teku",
      link: {
        type: "generated-index",
        title: "Test API",
        slug: "/category/test-api",
      },
      // @ts-ignore
      // eslint-disable-next-line global-require
      items: require("./docs/test-api/sidebar.js"),
      // items: [
      //   {
      //     type: "autogenerated",
      //     dirName: "test-api", // '.' means the current docs folder
      //   },
      // ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
